"""Per-variant config for the Garage Ledger workbook family.

Master (generic) + 5 build-type variants. Each variant shares the same
7-sheet workbook structure (README, BUILD INFO, EXPENSE LOG, PARTS
INVENTORY, TIMELINE, DASHBOARD, ROI). Only the pre-filled categories,
milestone phases, sample expense rows, and BUILD INFO defaults change.
"""

# Shared category list — used as the union behind the DASHBOARD pivot.
# Every variant exposes a subset (or the full list, for the master).
ALL_CATEGORIES = [
    "Engine", "Transmission", "Drivetrain", "Suspension", "Brakes",
    "Electrical / Wiring", "Fuel System", "Cooling", "Exhaust",
    "Intake / Tune", "Body / Paint", "Interior", "Wheels / Tires",
    "Glass / Trim", "HVAC", "Safety / Cage", "Recovery / Off-road",
    "Camp / Sleep", "Comms / Nav", "Tools", "Outside Labor",
    "DIY Hours (logged)", "Shipping / Freight", "Permits / Inspection",
    "Misc",
]


VARIANTS = {
    "master": {
        "slug": "master",
        "display_name": "Garage Ledger Pro",
        "xlsx_basename": "Garage-Ledger-Pro-v1.xlsx",
        "tagline": "Track every dollar in your build.",
        "default_vehicle": {
            "year": 2024,
            "make": "Vehicle Make",
            "model": "Model",
            "vin": "",
            "build_type": "Project Build",
            "start_date": "01/01/2026",
            "target_date": "12/31/2026",
            "build_budget": 25000,
            "target_sale_value": 35000,
            "shop_rate": 75,
            "roi_target_pct": 0.20,
        },
        # Master ships with the full category list so any build fits
        "categories": ALL_CATEGORIES,
        # Generic milestone phases — adapt per project
        "milestones": [
            ("Project kickoff", "Project kickoff: scope, budget, donor secured"),
            ("Tear-down", "Strip to bare bones, photograph everything"),
            ("Major component install", "Engine / drivetrain / chassis work"),
            ("Sub-system completion", "Suspension, brakes, fuel, cooling done"),
            ("Wiring + electronics", "Harness routed, accessories wired"),
            ("Body + paint", "Bodywork, prep, paint, reassembly"),
            ("First start / shakedown", "Initial fire-up, leak check, basic tune"),
            ("Dial-in / dyno / road-test", "Final tuning, alignment, shakedown miles"),
            ("Project complete", "Photos, walkaround video, listing prep"),
        ],
        "sample_expenses": [
            ("01/05/2026", "Engine", "RockAuto", "—", "Sample: gasket set", 1, 145.00),
            ("01/12/2026", "Suspension", "Summit Racing", "—", "Sample: coilover kit", 1, 1250.00),
            ("01/20/2026", "DIY Hours (logged)", "Self", "—", "Sample: 12 hr tear-down", 12, 75.00),
        ],
        # (part_num, description, vendor, qty, location, install_date, warranty_months, status)
        "sample_parts": [
            ("MAH-9456", "Engine gasket set, full", "RockAuto", 1, "Shelf A2", "01/05/2026", 24, "Installed"),
            ("BC-CR-V2", "Coilover kit, front + rear", "BC Racing", 4, "Floor bay 3", "01/12/2026", 12, "Installed"),
            ("OEM-12345", "Replacement brake rotors, pair", "Local dealer", 2, "Shelf B1", "", 24, "On Shelf"),
            ("FILT-OE45", "Oil filter (case of 6)", "RockAuto", 6, "Shelf C3", "", 0, "On Shelf"),
        ],
    },

    "ls_swap": {
        "slug": "ls-swap",
        "display_name": "Garage Ledger — LS Swap",
        "xlsx_basename": "Garage-Ledger-LS-Swap-v1.xlsx",
        "tagline": "Cost-track a full LS engine swap from donor to dyno.",
        "default_vehicle": {
            "year": 1985, "make": "Chevrolet", "model": "Camaro",
            "vin": "", "build_type": "LS Swap",
            "start_date": "01/01/2026", "target_date": "10/31/2026",
            "build_budget": 18000, "target_sale_value": 32000,
            "shop_rate": 75, "roi_target_pct": 0.30,
        },
        "categories": [
            "Engine (LS short/long block)",
            "Trans (T56 / 4L60E / 4L80E)",
            "Drivetrain (driveshaft / diff)",
            "Wiring Harness + ECU",
            "Fuel System (LS-spec)",
            "Cooling (radiator / fans)",
            "Exhaust (headers / mids / cat-back)",
            "Mounts / Crossmember",
            "Pedals / Hydraulics",
            "Tune (dyno + datalog)",
            "Tools / Adapters",
            "DIY Hours (logged)",
            "Outside Labor",
            "Shipping / Freight",
            "Misc",
        ],
        "milestones": [
            ("Donor secured", "LS engine + trans sourced, condition documented"),
            ("Bay prepped", "Old drivetrain out, bay cleaned + painted"),
            ("Mounts + crossmember", "LS mounts fitted, trans crossmember in"),
            ("Drop-in fitment", "Engine + trans test-fit, clearance checks"),
            ("Wiring harness", "Standalone harness routed, ECU mounted, sensors plugged"),
            ("Fuel + cooling", "High-pressure fuel system, radiator + fans wired"),
            ("Exhaust + driveshaft", "Headers + exhaust fab/install, driveshaft fitted"),
            ("First fire", "Coolant, oil, fuel, prime, key-on, start"),
            ("Tune complete", "Initial cold start map, drive-cycle datalog, dyno tune"),
        ],
        "sample_expenses": [
            ("01/10/2026", "Engine (LS short/long block)", "Local pull-yard", "—", "5.3L LM7 + 4L60E pulled together", 1, 1800.00),
            ("01/22/2026", "Wiring Harness + ECU", "Speartech", "—", "Standalone LS harness service", 1, 595.00),
            ("02/05/2026", "Mounts / Crossmember", "Holley", "—", "LS swap mount + crossmember kit", 1, 425.00),
            ("02/14/2026", "DIY Hours (logged)", "Self", "—", "Bay prep + paint, 16 hr", 16, 75.00),
        ],
        "sample_parts": [
            ("CHV-5.3LM7", "LS engine 5.3L LM7 + 4L60E", "Local pull-yard", 1, "Bay 3 floor", "01/10/2026", 0, "Installed"),
            ("SPT-STAND-LS", "Standalone LS harness, service", "Speartech", 1, "Box A1", "01/28/2026", 12, "Installed"),
            ("HOL-12612", "LS swap mount + crossmember kit", "Holley", 1, "Shelf B2", "02/05/2026", 12, "Installed"),
            ("HOOK-1850", "LS long-tube headers", "Hooker BlackHeart", 1, "Shelf C1", "", 6, "On Shelf"),
        ],
    },

    "cummins_swap": {
        "slug": "cummins-swap",
        "display_name": "Garage Ledger — Cummins Swap",
        "xlsx_basename": "Garage-Ledger-Cummins-Swap-v1.xlsx",
        "tagline": "Track every part of a 12V/24V/CR Cummins conversion.",
        "default_vehicle": {
            "year": 1995, "make": "Ford", "model": "F-250",
            "vin": "", "build_type": "Cummins Swap",
            "start_date": "01/01/2026", "target_date": "12/31/2026",
            "build_budget": 28000, "target_sale_value": 48000,
            "shop_rate": 85, "roi_target_pct": 0.35,
        },
        "categories": [
            "Cummins Engine (12V/24V/CR)",
            "Trans (NV4500 / 47RE / G56 / Allison)",
            "Transfer Case + Adapter",
            "Drivetrain (driveshafts / diffs)",
            "Fuel System (lift pump / lines / tank)",
            "Cooling (HD radiator / intercooler)",
            "Intake + Turbo",
            "Exhaust (downpipe / 4\" or 5\")",
            "Mounts / Conversion Hardware",
            "Wiring (PCM / accessories)",
            "Gauges + Monitoring",
            "Tune (TST / EFILive / etc.)",
            "DIY Hours (logged)",
            "Outside Labor (machine shop)",
            "Shipping / Freight",
            "Misc",
        ],
        "milestones": [
            ("Donor engine secured", "Cummins long block + trans + accessories sourced"),
            ("Recipient prepped", "Original drivetrain pulled, bay scrubbed"),
            ("Adapter / mounts fab", "Bellhousing adapter, motor mounts, trans crossmember"),
            ("Drop-in + driveline", "Engine in, trans + transfer case mated, driveshafts cut"),
            ("Fuel system", "Lift pump, supply/return lines, fuel filter, sump or draw straw"),
            ("Cooling + intake", "HD radiator, intercooler, charge pipes, air intake"),
            ("Exhaust + turbo plumbing", "Downpipe, 4\" or 5\" exhaust, wastegate / BOV if applicable"),
            ("Wiring + gauges", "Power, ground, crank/cam sensors, EGT + boost + fuel pressure gauges"),
            ("First fire + tune", "Prime fuel, bleed lines, fire, idle, drive, tune"),
        ],
        "sample_expenses": [
            ("01/15/2026", "Cummins Engine (12V/24V/CR)", "Diesel salvage", "—", "12V 5.9L w/ P-pump, 180K mi", 1, 4500.00),
            ("01/28/2026", "Trans (NV4500 / 47RE / G56 / Allison)", "Wholesale Drivetrain", "—", "NV4500 rebuilt + Cummins adapter plate", 1, 2950.00),
            ("02/10/2026", "Fuel System (lift pump / lines / tank)", "FASS", "—", "FASS 165 lift pump + supply line kit", 1, 685.00),
            ("02/18/2026", "DIY Hours (logged)", "Self", "—", "Drivetrain pull + adapter fab, 28 hr", 28, 85.00),
        ],
        "sample_parts": [
            ("CUM-5.9P", "12V 5.9L Cummins, P-pump, 180K mi", "Diesel salvage", 1, "Bay 2 floor", "01/15/2026", 0, "Installed"),
            ("NV-4500-R", "NV4500 rebuilt + Cummins adapter", "Wholesale Drivetrain", 1, "Shelf A1", "01/28/2026", 12, "Installed"),
            ("FASS-165", "FASS 165 lift pump + supply kit", "FASS", 1, "Shelf B2", "02/10/2026", 24, "Installed"),
            ("EXH-4DP-CR", "4\" downpipe + 4\" exhaust kit", "Diamond Eye", 1, "Shelf C3", "", 12, "On Shelf"),
        ],
    },

    "overland": {
        "slug": "overland",
        "display_name": "Garage Ledger — Overland Rig",
        "xlsx_basename": "Garage-Ledger-Overland-Rig-v1.xlsx",
        "tagline": "Every dollar — lift, rack, sleep system, recovery, comms.",
        "default_vehicle": {
            "year": 2014, "make": "Toyota", "model": "4Runner Trail",
            "vin": "", "build_type": "Overland Rig",
            "start_date": "01/01/2026", "target_date": "06/30/2026",
            "build_budget": 22000, "target_sale_value": 0,
            "shop_rate": 65, "roi_target_pct": 0.0,
        },
        "categories": [
            "Suspension (lift / shocks / UCAs)",
            "Skid Plates / Sliders",
            "Tires + Wheels",
            "Roof Rack / Awning",
            "Bumpers / Winch",
            "Recovery Gear (straps / boards / shovel)",
            "Lighting (aux / camp)",
            "Comms (HAM / GMRS / Starlink)",
            "Navigation (GPS / Gaia / OnX)",
            "Sleep System (RTT / wedge / camper)",
            "Cooking / Water",
            "Power (dual battery / solar / inverter)",
            "Storage / Drawers / Molle",
            "DIY Hours (logged)",
            "Outside Labor",
            "Shipping / Freight",
            "Misc",
        ],
        "milestones": [
            ("Vehicle baseline", "Maintenance current, baseline weight + measurements"),
            ("Suspension + tires", "Lift, shocks, UCAs, regear (if needed), tires + wheels"),
            ("Armor", "Skids, sliders, bumpers"),
            ("Recovery + lighting", "Winch, recovery gear, aux + ditch + camp lights"),
            ("Roof rack + storage", "Rack, awning, drawers, molle, tie-downs"),
            ("Sleep + cooking", "RTT or wedge, water, stove, fridge, table"),
            ("Power + comms", "Dual battery, solar, inverter, radios, antennae"),
            ("Navigation + media", "Mounts, GPS, Starlink, dash cam"),
            ("Shakedown trip", "Local trip, address every gap, dial it in"),
        ],
        "sample_expenses": [
            ("01/08/2026", "Suspension (lift / shocks / UCAs)", "ICON Vehicle Dynamics", "—", "ICON 0-3.5\" stage 6 kit", 1, 3850.00),
            ("01/20/2026", "Tires + Wheels", "Discount Tire", "—", "BFG KO2 285/70R17 (5)", 5, 285.00),
            ("02/02/2026", "Roof Rack / Awning", "Prinsu / ARB", "—", "Prinsu rack + ARB 2000 awning", 1, 1450.00),
            ("02/14/2026", "DIY Hours (logged)", "Self", "—", "Suspension install + alignment trip, 8 hr", 8, 65.00),
        ],
        "sample_parts": [
            ("ICON-S6-4R", "ICON 0-3.5\" stage 6 lift kit", "ICON Vehicle Dynamics", 1, "Bay 1 floor", "01/15/2026", 60, "Installed"),
            ("BFG-KO2-285", "BFG KO2 285/70R17 (5 incl spare)", "Discount Tire", 5, "Wheel rack", "01/20/2026", 6, "Installed"),
            ("PRINSU-4R5", "Prinsu roof rack", "Prinsu Design", 1, "Garage ceiling", "02/02/2026", 60, "Installed"),
            ("ARB-2000", "ARB awning 2000", "ARB USA", 1, "On rack", "02/02/2026", 24, "Installed"),
        ],
    },

    "restomod": {
        "slug": "restomod",
        "display_name": "Garage Ledger — Restomod",
        "xlsx_basename": "Garage-Ledger-Restomod-v1.xlsx",
        "tagline": "Classic chassis, modern drivetrain — every receipt logged.",
        "default_vehicle": {
            "year": 1969, "make": "Chevrolet", "model": "C10",
            "vin": "", "build_type": "Restomod",
            "start_date": "01/01/2026", "target_date": "06/30/2027",
            "build_budget": 45000, "target_sale_value": 75000,
            "shop_rate": 85, "roi_target_pct": 0.25,
        },
        "categories": [
            "Chassis / Frame",
            "Engine + Trans (modern swap)",
            "Suspension (IFS / IRS / coilovers)",
            "Brakes (disc conversion / big brake)",
            "Steering (rack-and-pinion)",
            "Rear End (housing / gears / posi)",
            "Fuel + Cooling",
            "Wiring (modern harness)",
            "Body / Sheet Metal",
            "Paint + Bodywork",
            "Glass / Trim / Weatherstrip",
            "Interior (seats / dash / carpet)",
            "Wheels / Tires",
            "DIY Hours (logged)",
            "Outside Labor (paint / upholstery)",
            "Shipping / Freight",
            "Misc",
        ],
        "milestones": [
            ("Frame off / cataloged", "Body lifted, frame inspected, parts cataloged"),
            ("Chassis upgrades", "IFS, rear-end, coilovers, rack-and-pinion, brakes"),
            ("Drivetrain installed", "Engine + trans + accessories on frame"),
            ("Body prep", "Strip, blast, panel rep, fitment dry-run"),
            ("Paint", "Color sanded, sealed, base, clear, cut + buff"),
            ("Reassembly mechanical", "Body on, glass set, trim fitted, hood + doors aligned"),
            ("Wiring + accessories", "Modern harness, HVAC, audio, gauges"),
            ("Interior", "Seats, dash, headliner, carpet, panels"),
            ("Shakedown + concours prep", "Detail, photo session, listing prep"),
        ],
        "sample_expenses": [
            ("01/12/2026", "Chassis / Frame", "Roadster Shop", "—", "Spec chassis with IFS + rear coilover setup", 1, 14500.00),
            ("01/25/2026", "Engine + Trans (modern swap)", "Chevrolet Performance", "—", "LT4 crate + 10L80 trans", 1, 24500.00),
            ("02/15/2026", "Paint + Bodywork", "Outside Labor (paint / upholstery)", "—", "Body shop deposit", 1, 5000.00),
            ("03/01/2026", "DIY Hours (logged)", "Self", "—", "Frame disassembly + cataloging, 40 hr", 40, 85.00),
        ],
        "sample_parts": [
            ("RS-SPEC-C10", "Roadster Shop spec chassis (IFS + coilover)", "Roadster Shop", 1, "Bay 1 floor", "02/01/2026", 60, "Installed"),
            ("CP-LT4-CRATE", "LT4 supercharged crate engine", "Chevrolet Performance", 1, "Engine stand A", "", 36, "On Shelf"),
            ("CP-10L80", "10L80 10-speed automatic", "Chevrolet Performance", 1, "Trans stand", "", 36, "On Shelf"),
            ("WIL-BBK-6P", "Wilwood 6-piston big brake kit, front", "Wilwood", 1, "Shelf C2", "", 24, "On Shelf"),
        ],
    },

    "track_build": {
        "slug": "track-build",
        "display_name": "Garage Ledger — Track Build",
        "xlsx_basename": "Garage-Ledger-Track-Build-v1.xlsx",
        "tagline": "Cage, brakes, suspension, seat — track every track-day dollar.",
        "default_vehicle": {
            "year": 2008, "make": "Mazda", "model": "MX-5 (NC)",
            "vin": "", "build_type": "Track Build",
            "start_date": "01/01/2026", "target_date": "09/30/2026",
            "build_budget": 14000, "target_sale_value": 22000,
            "shop_rate": 75, "roi_target_pct": 0.15,
        },
        "categories": [
            "Roll Cage / Harness Bar",
            "Seats + Harnesses",
            "Suspension (coilovers / sways / bushings)",
            "Brakes (pads / rotors / lines / fluid)",
            "Brake Cooling Ducts",
            "Wheels / Track Tires",
            "Alignment / Corner Balance",
            "Cooling (radiator / oil cooler)",
            "Engine (intake / exhaust / tune)",
            "Differential (LSD / fluids)",
            "Weight Reduction",
            "Safety Gear (fire / nets / killswitch)",
            "Track Day Fees",
            "Trailer / Transport",
            "DIY Hours (logged)",
            "Outside Labor (cage / alignment)",
            "Shipping / Freight",
            "Misc",
        ],
        "milestones": [
            ("Baseline car prep", "Maintenance current, fluids fresh, baseline lap times"),
            ("Brakes + cooling", "Pads, rotors, lines, fluid, ducts, cooler"),
            ("Suspension + alignment", "Coilovers, swaybars, bushings, corner balance"),
            ("Safety", "Cage, seat, harness, nets, killswitch, fire system"),
            ("Tires + wheels", "Track wheels, R-comps, mounted + balanced"),
            ("Powertrain dial-in", "Intake, exhaust, tune, diff"),
            ("Weight reduction", "Strip non-essentials, balance, document weight delta"),
            ("Shakedown laps", "First track session, address brake fade / handling / heat"),
            ("Season-ready", "Spares stocked, trailer dialed in, ready for full season"),
        ],
        "sample_expenses": [
            ("01/15/2026", "Roll Cage / Harness Bar", "Outside Labor (cage / alignment)", "—", "Cage shop deposit (6-pt bolt-in)", 1, 1850.00),
            ("01/22/2026", "Suspension (coilovers / sways / bushings)", "Bilstein / Eibach", "—", "Bilstein PSS10 + Eibach swaybars", 1, 2450.00),
            ("02/01/2026", "Brakes (pads / rotors / lines / fluid)", "Hawk / StopTech", "—", "Hawk DTC-60 + StopTech rotors + SS lines + Castrol SRF", 1, 1280.00),
            ("02/14/2026", "DIY Hours (logged)", "Self", "—", "Brake + suspension install, 14 hr", 14, 75.00),
        ],
        "sample_parts": [
            ("BIL-PSS10-NC", "Bilstein PSS10 coilovers, full set", "Bilstein", 4, "Shelf A1", "01/22/2026", 24, "Installed"),
            ("EIB-SWAY-NC", "Eibach anti-roll bars, front + rear", "Eibach", 2, "Shelf A2", "01/22/2026", 24, "Installed"),
            ("HAWK-DTC60", "Hawk DTC-60 brake pads, front + rear", "Hawk", 2, "Shelf B1", "02/01/2026", 0, "Installed"),
            ("SPARCO-EVO", "Sparco EVO Carbon FIA seat", "Sparco USA", 1, "Box on shelf C2", "", 60, "On Shelf"),
        ],
    },
}
